linters:
  enable:
    - deadcode
    - depguard
    - dupl
    - errcheck
    - gochecknoinits
    - goconst
    - gocritic
    - gofmt
    - goimports
    - golint
    - gosimple
    - govet
    - ineffassign
    - interfacer
    - lll
    - misspell
    - nakedret
    - scopelint
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
