project_name: git-info
before:
  hooks:
    - go mod download
builds:
- env:
  - CGO_ENABLED=0
  main: ./cmd/git-info/git-info.go
  goos:
    - darwin
    - linux
    - freebsd
    - windows
  goarch:
    - amd64
    - arm
    - ppc64le
  goarm:
    - 6
    - 7
archive:
  format: binary
  files:
    - LICENSE*
    - README*
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      # CHANGELOG worthy:
      # feat: add beta sequence
      # fix: remove broken confirmation message
      # refactor: share logic between 4d3d3d3 and flarhgunnstow
      # perf: improved performance of the zabbit
      #
      # NOISE:
      # chore: add Oyster build script
      # docs: explain hat wobble
      # lint: convert tabs to spaces
      # style: convert tabs to spaces
      # test: ensure Tayne retains clothing
    - '(?i)^(chore|docs|lint|style|test)'
    - '(?i)typo|thinko'
release:
  github:
    owner: docwhat
    name: git-info
  name_template: "{{ .ProjectName }}-v{{ .Version }} {{ .Env.USER }}"
# brew:
#   github:
#     owner: docwhat
#     name: homebrew-tap
#   folder: Formula
#   homepage:  https://github.com/docwhat/go-git-info
#   description: Fast git information for your shell prompt
#   test: |
#     system "#{bin}/git-info -v"
