default_language_version:
  golang: "1.12"
default_stages: ["commit", "commit-msg"]

repos:
- repo: "local"
  hooks:
    - id: "semantic-commit-message"
      name: "semantic commit messages"
      language: "script"
      entry: "script/commit-msg-check"
      stages: ["commit-msg"]
    - id: "golangci-lint"
      name: "golang CI linter"
      language: "script"
      entry: "bin/golangci-lint"
      args: ["run", "./..."]
      files: \.go$
      stages: ["commit"]
