#!/bin/bash

set -eEuo pipefail

if [[ -z ${CI:-} ]]; then
  if ! command -v >/dev/null; then
    echo "Please install an LTS version of Node.js"
    echo "        https://nodejs.org/en/"
    exit 10
  fi

  yarn install
fi

curl -sSfL \
  https://install.goreleaser.com/github.com/golangci/golangci-lint.sh |
  sh -s v1.15.0

# EOF
